apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: docker.io/duy290410/tmc:v01
          imagePullPolicy: Always
          
          apiVersion: networking.k8s.io/v1


kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: traefik
  labels:
    app: demo-app
  name: demo-app
  namespace: master
spec:
  rules:
  - host: duy.com
    http:
      paths:
      - backend:
          service:
            name: demo-app-svc
            port: 
              number: 8888
        path: /
        pathType: Prefix  
  tls:
  - hosts:
    - duy.com
    secretName: demo-app-tls


apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
  namespace: master
spec:
  selector:
    app: demo-app
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP