apiVersion: v1
kind: Secret
metadata:
  name: tripota-acr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {
      "auths": {
        "https://tripotadevacr.azurecr.io": {
          "auth": "VHJpcE9UQURldkFDUjpPTGFzckZIOFoxOHFLcnVOY0d3Z3Z2V0hiUUNsMkhXSGNzWWlrUGFCUGMrQUNSQ2RYQTVT"
        }
      }
    }